# Generated by Django 5.0.1 on 2024-01-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_rename_body_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='email',
            field=models.EmailField(default='something', max_length=255),
        ),
    ]
