# Generated by Django 5.0.1 on 2024-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_reguser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='cpassword',
            field=models.CharField(default='something', max_length=100),
        ),
    ]
