# Generated by Django 5.0.1 on 2024-01-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_reguser_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
